// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Pb.Wechat.EntityFrameworkCore;
using System;

namespace Pb.Wechat.Migrations.GroupMessageDb
{
    [DbContext(typeof(GroupMessageDbContext))]
    [Migration("20180311014813_add_table_msg")]
    partial class add_table_msg
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pb.Wechat.TaskGroupMessages.TaskGroupMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClearedOpenIDs");

                    b.Property<DateTime>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<string>("ErrCode");

                    b.Property<string>("ErrMsg");

                    b.Property<int>("FailCount");

                    b.Property<int>("GroupID");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<int>("MessageID");

                    b.Property<int>("MpID");

                    b.Property<string>("MsgDataID");

                    b.Property<string>("OpenIDs");

                    b.Property<int>("SendCount");

                    b.Property<int>("SuccessCount");

                    b.Property<string>("TaskID");

                    b.Property<int>("TaskState");

                    b.Property<string>("WxMsgID");

                    b.HasKey("Id");

                    b.ToTable("TaskGroupMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
