// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Pb.Wechat.EntityFrameworkCore;
using System;

namespace Pb.Wechat.Migrations.CYDb
{
    [DbContext(typeof(CYDbContext))]
    [Migration("20180311082411_changecyproblem")]
    partial class changecyproblem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pb.Wechat.CYConfigs.CYConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnswerTemplete");

                    b.Property<string>("CloseProblemText");

                    b.Property<string>("CreateProblemPreText");

                    b.Property<int>("CreateProblemPreTextLength");

                    b.Property<string>("CreateProblemText");

                    b.Property<int>("NoOperationCloseMinute");

                    b.Property<int>("NoOperationMinute");

                    b.Property<string>("NoOperationText");

                    b.HasKey("Id");

                    b.ToTable("CYConfigs");
                });

            modelBuilder.Entity("Pb.Wechat.CYDoctors.CYDoctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CYId");

                    b.Property<string>("Clinic");

                    b.Property<string>("ClinicNO");

                    b.Property<DateTime>("CreationTime");

                    b.Property<string>("GoodAt");

                    b.Property<string>("Hospital");

                    b.Property<string>("HospitalGrand");

                    b.Property<string>("Image");

                    b.Property<string>("LevelTitle");

                    b.Property<string>("Name");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("CYId");

                    b.ToTable("CYDoctors");
                });

            modelBuilder.Entity("Pb.Wechat.CYProblemContents.CYProblemContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Age");

                    b.Property<DateTime>("CreationTime");

                    b.Property<int?>("DoctorId");

                    b.Property<string>("File");

                    b.Property<int>("ProblemId");

                    b.Property<int>("SendUser");

                    b.Property<string>("Sex");

                    b.Property<string>("Text");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.ToTable("CYProblemContents");
                });

            modelBuilder.Entity("Pb.Wechat.CYProblems.CYProblem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CYProblemId");

                    b.Property<DateTime>("CreationTime");

                    b.Property<int>("FansId");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<string>("OpenId");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.ToTable("CYProblems");
                });
#pragma warning restore 612, 618
        }
    }
}
