// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Pb.Wechat.EntityFrameworkCore;
using System;

namespace Pb.Wechat.Migrations.KfDb
{
    [DbContext(typeof(KfDbContext))]
    [Migration("20180409061241_add_customer_online_columns")]
    partial class add_customer_online_columns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pb.Wechat.CustomerServiceConversationMsgs.CustomerServiceConversationMsg", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<int?>("CustomerId");

                    b.Property<int?>("FanId");

                    b.Property<string>("MediaId");

                    b.Property<string>("MediaUrl");

                    b.Property<int>("MpID");

                    b.Property<string>("MsgContent");

                    b.Property<int>("MsgType");

                    b.Property<int>("Sender");

                    b.HasKey("Id");

                    b.ToTable("CustomerServiceConversationMsgs");
                });

            modelBuilder.Entity("Pb.Wechat.CustomerServiceConversations.CustomerServiceConversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<int?>("CustomerId");

                    b.Property<string>("CustomerOpenId");

                    b.Property<DateTime?>("EndTalkTime");

                    b.Property<int?>("FanId");

                    b.Property<string>("FanOpenId");

                    b.Property<long?>("LastConversationId");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<int>("MpID");

                    b.Property<DateTime?>("StartTalkTime");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.ToTable("CustomerServiceConversations");
                });

            modelBuilder.Entity("Pb.Wechat.CustomerServiceOnlines.CustomerServiceOnline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AutoJoin");

                    b.Property<int>("AutoJoinCount");

                    b.Property<string>("ConnectId");

                    b.Property<int>("ConnectState");

                    b.Property<DateTime>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<string>("InviteExpireTime");

                    b.Property<string>("InviteStatus");

                    b.Property<string>("InviteWx");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("KfAccount");

                    b.Property<string>("KfHeadingUrl");

                    b.Property<string>("KfId");

                    b.Property<string>("KfNick");

                    b.Property<string>("KfPassWord");

                    b.Property<string>("KfWx");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("LocalHeadFilePath");

                    b.Property<string>("LocalHeadingUrl");

                    b.Property<string>("MessageToken");

                    b.Property<int>("MpID");

                    b.Property<int>("OnlineState");

                    b.Property<string>("OpenID");

                    b.Property<string>("PreKfAccount");

                    b.Property<string>("PublicNumberAccount");

                    b.HasKey("Id");

                    b.ToTable("CustomerServiceOnlines");
                });

            modelBuilder.Entity("Pb.Wechat.CustomerServicePrivateResponseTexts.CustomerServicePrivateResponseText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("MediaId");

                    b.Property<int>("MpID");

                    b.Property<string>("OpenID");

                    b.Property<string>("PreviewImgUrl");

                    b.Property<string>("ReponseContentType");

                    b.Property<string>("ResponseText");

                    b.Property<string>("ResponseType");

                    b.Property<int>("UseCount");

                    b.HasKey("Id");

                    b.ToTable("CustomerServicePrivateResponseTexts");
                });

            modelBuilder.Entity("Pb.Wechat.CustomerServiceResponseTexts.CustomerServiceResponseText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("MediaId");

                    b.Property<int>("MpID");

                    b.Property<string>("PreviewImgUrl");

                    b.Property<string>("ReponseContentType");

                    b.Property<string>("ResponseText");

                    b.Property<string>("ResponseType");

                    b.Property<int>("UseCount");

                    b.HasKey("Id");

                    b.ToTable("CustomerServiceResponseTexts");
                });

            modelBuilder.Entity("Pb.Wechat.CustomerServiceWorkTimes.CustomerServiceWorkTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AfternoonEndHour");

                    b.Property<string>("AfternoonEndMinute");

                    b.Property<string>("AfternoonStartHour");

                    b.Property<string>("AfternoonStartMinute");

                    b.Property<DateTime>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("MorningEndHour");

                    b.Property<string>("MorningEndMinute");

                    b.Property<string>("MorningStartHour");

                    b.Property<string>("MorningStartMinute");

                    b.Property<int>("MpID");

                    b.Property<string>("WeekDay");

                    b.HasKey("Id");

                    b.ToTable("CustomerServiceWorkTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
